### PR TITLE
maru: Change Android.mk to Android.bp

### PR DESCRIPTION
**Pull request by utzcoz**
It uses the similar method of [lxc-android](https://github.com/ppoffice/lxc-android).

I have tested it with pixel building and `lxc-start --name default`  and `lxc-stop --name default`.

### CODE REVIEW

**Comment by utzcoz** [comment]
@pdsouza @pintaf , could you help to test it with your devices? Thanks.

**Comment by pintaf** [comment]
I'll check whenever I get the time (just landed in family for 20 days, won't be that much on my computer).
I'll also check your mcprepare changes.
FYI, here is the [platform_external_lxc](https://github.com/pintaf/lxc-android/tree/maru-0.7-lxc1) I got working.
My changes were mainly by trial and error. So it might seems weird, but it was working.

**Comment by pintaf** [comment]
@utzcoz All good. You're a chief!
Mcprepare unpacked the image on first boot and I was able to start and log into the container.
Merry chrismas !

**Review by pdsouza — APPROVED** [review]
Looks great!

**Comment by pdsouza** [comment]
Thanks @utzcoz for converting to Android.bp and for testing @pintaf! I haven't had a chance to test on my own devices over the holidays but if it works for both of you this should be good. Merging in for now so everyone can easily test this out.

**Comment by pdsouza** [comment]
Confirmed that `external/lxc` builds fine with `Android.bp` for `hammerhead`.

**Pull request merged**
